# Generated by Django 3.0.1 on 2020-07-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200710_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='classenrollment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='classenrollment',
            unique_together={('student_id', 'class_id')},
        ),
    ]
