# Generated by Django 3.0.1 on 2020-07-12 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200710_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionsresources',
            name='resource_image',
            field=models.ImageField(blank=True, null=True, upload_to='correction_resources/', verbose_name='Image Resource (optional)'),
        ),
        migrations.AddField(
            model_name='correctionsresources',
            name='resource_video',
            field=models.FileField(blank=True, null=True, upload_to='correction_resources/', verbose_name='File Resouce (optional)'),
        ),
        migrations.AddField(
            model_name='homeworkresources',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeworkresources',
            name='resource_image',
            field=models.ImageField(blank=True, null=True, upload_to='HomeworkResources/%m/%d/', verbose_name='Image Resource (optional)'),
        ),
        migrations.AddField(
            model_name='homeworkresources',
            name='resource_video',
            field=models.FileField(blank=True, null=True, upload_to='HomeworkResources/%m/%d/', verbose_name='File Resouce (optional)'),
        ),
        migrations.AddField(
            model_name='homeworkresources',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submissionresources',
            name='resource_image',
            field=models.ImageField(blank=True, null=True, upload_to='SubmissionResources/', verbose_name='Image Resource (optional)'),
        ),
        migrations.AddField(
            model_name='submissionresources',
            name='resource_video',
            field=models.FileField(blank=True, null=True, upload_to='SubmissionResources/', verbose_name='File Resouce (optional)'),
        ),
        migrations.AlterField(
            model_name='correctionsresources',
            name='resource_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='correctionsresources',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('image', 'image'), ('file', 'file'), ('text', 'text')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkresources',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='HomeworkResources/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='homeworkresources',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('image', 'image'), ('file', 'file'), ('text', 'text')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='photo',
            field=models.ImageField(max_length=250, upload_to='schoolimages/school_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(max_length=250, upload_to='Student/student_photos/'),
        ),
        migrations.AlterField(
            model_name='submissionresources',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('image', 'image'), ('file', 'file'), ('text', 'text')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(max_length=250, upload_to='Teacher/teacher_photos/'),
        ),
    ]
