# Generated by Django 3.0.1 on 2020-07-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200712_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionsresources',
            name='resource_File',
            field=models.FileField(blank=True, null=True, upload_to='correction_resources/', verbose_name='File Resouce (optional)'),
        ),
        migrations.AddField(
            model_name='homeworkresources',
            name='resource_File',
            field=models.FileField(blank=True, null=True, upload_to='HomeworkResources/%m/%d/', verbose_name='File Resouce (optional)'),
        ),
        migrations.AddField(
            model_name='submissionresources',
            name='resource_File',
            field=models.FileField(blank=True, null=True, upload_to='SubmissionResources/', verbose_name='File Resouce (optional)'),
        ),
        migrations.AlterField(
            model_name='correctionsresources',
            name='resource_video',
            field=models.FileField(blank=True, null=True, upload_to='correction_resources/', verbose_name='Video Resouce (optional)'),
        ),
        migrations.AlterField(
            model_name='homeworkresources',
            name='resource_video',
            field=models.FileField(blank=True, null=True, upload_to='HomeworkResources/%m/%d/', verbose_name='Video Resouce (optional)'),
        ),
        migrations.AlterField(
            model_name='submissionresources',
            name='resource_video',
            field=models.FileField(blank=True, null=True, upload_to='SubmissionResources/', verbose_name='Video Resouce (optional)'),
        ),
    ]
